version: '3.1'

services:

  meals-db:
   image: postgres
   expose:
   - "5432"
   ports:
   - "5432:5432"
   volumes:
   - $HOME/data/postgres:/var/lib/postgresql/data
   hostname: meals-db
   environment:
    - POSTGRES_PASSWORD=postgres

  planner-db:
   image: mongo
   expose:
   - "27017"
   ports:
   - "27017:27017"
   volumes:
   - $HOME/data/mongo:/data/db
   hostname: planner-db