version: '3.1'

services:

  meals-db:
   image: postgres
   environment:
     POSTGRES_PASSWORD: postgres
   expose:
   - "5432"
   ports:
   - "5432:5432"
   volumes:
   - /home/mansur/data/postgres:/var/lib/postgresql/data
   hostname: meals-db
   environment:
    - POSTGRES_PASSWORD=postgres

  meals-service:
   build:
    context: ./modules/meals
   expose:
   - "8080"
   ports:
   - "8080:8080"
   hostname: meals-service
   links:
   - meals-db

  planner-db:
   image: mongo
   expose:
   - "27017"
   ports:
   - "27017:27017"
   volumes:
   - /home/mansur/data/mongo:/data/db
   hostname: planner-db
   #links:
   #- res

  planner-service:
   build:
    context: ./modules/planner
   expose:
   - "8081"
   ports:
   - "8081:8081"
   hostname: planner-service
   links:
   - planner-db
